// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtIstCzrJOB0-XwupI1JkwhhDA5couGT4',
    appId: '1:809530917468:web:01fd333d5146fdc9ea1c99',
    messagingSenderId: '809530917468',
    projectId: 'hann-7b7be',
    authDomain: 'hann-7b7be.firebaseapp.com',
    databaseURL: 'https://hann-7b7be-default-rtdb.firebaseio.com',
    storageBucket: 'hann-7b7be.firebasestorage.app',
    measurementId: 'G-F5273WDZCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgBOajHqUAjkoM2hx3t2nPS1s9_B94WiQ',
    appId: '1:809530917468:android:846a968ac98f7942ea1c99',
    messagingSenderId: '809530917468',
    projectId: 'hann-7b7be',
    databaseURL: 'https://hann-7b7be-default-rtdb.firebaseio.com',
    storageBucket: 'hann-7b7be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9jFGW9JmBxudXcifOZF-tIw5YXXY-P-E',
    appId: '1:809530917468:ios:933ca84a04f6b32dea1c99',
    messagingSenderId: '809530917468',
    projectId: 'hann-7b7be',
    databaseURL: 'https://hann-7b7be-default-rtdb.firebaseio.com',
    storageBucket: 'hann-7b7be.firebasestorage.app',
    iosBundleId: 'com.example.hanTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9jFGW9JmBxudXcifOZF-tIw5YXXY-P-E',
    appId: '1:809530917468:ios:933ca84a04f6b32dea1c99',
    messagingSenderId: '809530917468',
    projectId: 'hann-7b7be',
    databaseURL: 'https://hann-7b7be-default-rtdb.firebaseio.com',
    storageBucket: 'hann-7b7be.firebasestorage.app',
    iosBundleId: 'com.example.hanTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtIstCzrJOB0-XwupI1JkwhhDA5couGT4',
    appId: '1:809530917468:web:acd1c788e1bc6528ea1c99',
    messagingSenderId: '809530917468',
    projectId: 'hann-7b7be',
    authDomain: 'hann-7b7be.firebaseapp.com',
    databaseURL: 'https://hann-7b7be-default-rtdb.firebaseio.com',
    storageBucket: 'hann-7b7be.firebasestorage.app',
    measurementId: 'G-CGYGC7492K',
  );
}
